// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24.09.2024, 21:39:44
const configMerger = require("C:/Users/adlet/OneDrive/Desktop/trello-board/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/adlet/OneDrive/Desktop/trello-board/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adlet/OneDrive/Desktop/trello-board/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adlet/OneDrive/Desktop/trello-board/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adlet/OneDrive/Desktop/trello-board/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adlet/OneDrive/Desktop/trello-board/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adlet/OneDrive/Desktop/trello-board/plugins/**/*.{js,ts,mjs}","C:/Users/adlet/OneDrive/Desktop/trello-board/composables/**/*.{js,ts,mjs}","C:/Users/adlet/OneDrive/Desktop/trello-board/utils/**/*.{js,ts,mjs}","C:/Users/adlet/OneDrive/Desktop/trello-board/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adlet/OneDrive/Desktop/trello-board/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adlet/OneDrive/Desktop/trello-board/app.config.{js,ts,mjs}"] }));

module.exports = config
